/**
 * Part II CST course catalog: term groupings, course metadata, and topic titles.
 * To add or rename courses, edit `COURSES_DATA` only — the app derives ordered lists from it.
 */
import type { Course, CourseWithTerm } from "../types";

export type TermId = "michaelmas" | "lent" | "easter";

export interface TermBucket {
  label: string;
  courses: Course[];
}

export const COURSES_DATA: Record<TermId, TermBucket> = {
  michaelmas: {
    label: "Michaelmas Term",
    courses: [
      {
        id: "bioinfo",
        name: "Bioinformatics",
        code: "",
        lecturer: "Prof Pietro Lio'",
        hours: 12,
        isModule: false,
        topics: [
          "Introduction to Biological Data & Adleman's Experiment",
          "Dynamic Programming: LCS, Global & Local Alignment",
          "Linear Space Alignment (Hirschberg)",
          "Nussinov Algorithm for RNA",
          "Heuristics for Multiple Alignment",
          "Sequence Database Search & BLAST",
          "Genome Sequencing & De Bruijn Graphs",
          "Phylogeny: Distance-Based Methods",
          "Phylogeny: Character-Based Methods",
          "Hidden Markov Models",
          "Stochastic Simulation (Doob-Gillespie)",
          "Revision & Example Class",
        ],
      },
      {
        id: "business",
        name: "Business Studies",
        code: "",
        lecturer: "McTavish & Harris",
        hours: 8,
        isModule: false,
        topics: [
          "Introduction to Business & Entrepreneurship",
          "Business Plans & Financial Basics",
          "Marketing & Strategy",
          "Intellectual Property & Patents",
          "Company Law & Governance",
          "Venture Capital & Funding",
          "Management & Leadership",
          "Case Studies & Exam Prep",
        ],
      },
      {
        id: "denotsem",
        name: "Denotational Semantics",
        code: "",
        lecturer: "Dr Ioannis Markakis",
        hours: 10,
        isModule: false,
        topics: [
          "Complete Partial Orders (CPOs)",
          "Continuous Functions & Fixed Points",
          "Scott Induction & Chain-Closed Subsets",
          "PCF: Syntax & Evaluation",
          "Contextual Equivalence",
          "Denotational Semantics of PCF Types",
          "Denotational Semantics of PCF Terms",
          "Compositionality & Soundness",
          "Computational Adequacy",
          "Full Abstraction & Parallel Or",
        ],
      },
      {
        id: "infotheory",
        name: "Information Theory",
        code: "",
        lecturer: "Dr Robert Harle",
        hours: 12,
        isModule: false,
        topics: [
          "Information, Probability & Shannon Information",
          "Entropy of Discrete Variables",
          "Joint Entropy & Mutual Information",
          "Source Coding Theorem & Data Compression",
          "Huffman Codes & Prefix Property",
          "Asymptotic Equipartition Principle",
          "Binary Symmetric Channels & Noiseless Capacity",
          "Noisy Channel Coding & Error-Correcting Codes",
          "Noisy Channel Coding Theorem",
          "Continuous Entropy & Gaussian Channels",
          "KL Divergence & Cross-Entropy",
          "Applications & Kolmogorov Complexity",
        ],
      },
      {
        id: "texjulia",
        name: "LaTeX and Julia",
        code: "",
        lecturer: "Dr Markus Kuhn",
        hours: 3,
        isModule: false,
        topics: [
          "LaTeX: Document Structure & Typesetting",
          "LaTeX: Maths, Figures & BibTeX",
          "Julia: Scientific Computing Intro",
        ],
      },
      {
        id: "princcomm",
        name: "Principles of Communications",
        code: "",
        lecturer: "Prof Jon Crowcroft",
        hours: 16,
        isModule: false,
        topics: [
          "Introduction & Network Abstractions",
          "Layering & Modular Functionality",
          "Information, Noise & Channel Capacity",
          "Topology & Routing (Graph Theory)",
          "Flow & Congestion Control",
          "End-to-End Protocols & TCP",
          "Shared Media & MAC Protocols",
          "Ethernet & Radio Networks",
          "Switched Networks",
          "QoS, Scheduling & Queue Management",
          "Naming, Addressing & DNS",
          "Security Principles in Networks",
          "Multicast & Overlay Networks",
          "Network Economics & Game Theory",
          "Network Management & Measurement",
          "Review & Advanced Topics",
        ],
      },
      {
        id: "types",
        name: "Types",
        code: "",
        lecturer: "Dr Neel Krishnaswami",
        hours: 12,
        isModule: false,
        topics: [
          "Simply-Typed Lambda Calculus (STLC)",
          "Products, Sums & Pattern Matching",
          "ML Type Inference (Algorithm W)",
          "Polymorphic Lambda Calculus (PLC) — Syntax",
          "PLC — Reduction & Datatypes",
          "PLC — Type Inference",
          "Monads & Effects",
          "References, Recursion & Looping",
          "Continuations & Classical Logic",
          "Continuation-Passing Style",
          "Dependent Types & Indexed Datatypes",
          "Equality Types & Proofs as Programs",
        ],
      },
      {
        id: "agip",
        name: "Advanced Graphics & Image Processing",
        code: "AGIP",
        lecturer: "Dr Rafal Mantiuk",
        hours: 16,
        isModule: true,
        topics: [
          "Image Filtering & Convolution",
          "Edge Detection & Feature Extraction",
          "Colour Spaces & Perception",
          "Tone Mapping & HDR Imaging",
          "Image Segmentation",
          "Texture Synthesis & Analysis",
          "Ray Tracing & Global Illumination",
          "GPU Rendering Pipelines",
        ],
      },
      {
        id: "aai",
        name: "Affective Artificial Intelligence",
        code: "AAI",
        lecturer: "Prof Hatice Gunes",
        hours: 16,
        isModule: true,
        topics: [
          "Affect, Emotion & Sentiment Models",
          "Facial Expression Recognition",
          "Speech & Audio Emotion Analysis",
          "Physiological Signal Processing",
          "Multimodal Affect Recognition",
          "Affective Computing Applications",
          "Ethics in Emotion AI",
          "Generative Models for Affect",
        ],
      },
      {
        id: "cat",
        name: "Category Theory",
        code: "CAT",
        lecturer: "Prof Marcelo Fiore",
        hours: 16,
        isModule: true,
        topics: [
          "IPL in Natural Deduction",
          "Semantics of IPL in a CCC Preorder",
          "STLC & Cartesian Closed Categories",
          "Curry-Howard-Lawvere Correspondence",
          "Functors & Natural Transformations",
          "Adjunctions & Universal Properties",
          "Dependent Types as Adjoint Functors",
          "Presheaves & the Yoneda Lemma",
          "Monads & Computational Lambda Calculus",
        ],
      },
      {
        id: "dsp",
        name: "Digital Signal Processing",
        code: "DSP",
        lecturer: "Dr Markus Kuhn",
        hours: 16,
        isModule: true,
        topics: [
          "Signals, Systems & Convolution",
          "Fourier Series & DFT",
          "Fast Fourier Transform (FFT)",
          "Z-Transform & Transfer Functions",
          "FIR & IIR Filter Design",
          "Windowing & Spectral Leakage",
          "Sampling, Aliasing & Reconstruction",
          "Multirate Processing & Interpolation",
        ],
      },
      {
        id: "mvp",
        name: "Machine Visual Perception",
        code: "MVP",
        lecturer: "Dr Oztireli & Dr Town",
        hours: 12,
        isModule: true,
        topics: [
          "Image Formation & Camera Models",
          "Feature Detection & Matching",
          "Stereo Vision & Depth Estimation",
          "Optical Flow & Motion Estimation",
          "Object Recognition & Classification",
          "Neural Networks for Vision",
        ],
      },
      {
        id: "nlp",
        name: "Natural Language Processing",
        code: "NLP",
        lecturer: "Dr Sun & Dr Chen",
        hours: 15,
        isModule: true,
        topics: [
          "Tokenization & Text Preprocessing",
          "Language Models & N-grams",
          "Word Embeddings (Word2Vec, GloVe)",
          "Sequence Models (RNNs, LSTMs)",
          "Attention Mechanisms & Transformers",
          "Pre-trained Models (BERT, GPT)",
          "Named Entity Recognition & POS Tagging",
          "Machine Translation",
        ],
      },
      {
        id: "hcai",
        name: "Practical Research in Human-centred AI",
        code: "HCAI",
        lecturer: "Prof Blackwell & Dr Sarkar",
        hours: 16,
        isModule: true,
        topics: [
          "Human-Centred AI Principles",
          "User Study Design & Methods",
          "Qualitative & Quantitative Analysis",
          "Interactive ML Systems",
          "Explainability & Interpretability",
          "AI Ethics & Responsible Design",
          "Prototyping AI Interfaces",
          "Research Paper Writing",
        ],
      },
      {
        id: "qct",
        name: "Quantum Complexity Theory",
        code: "QCT",
        lecturer: "Prof Tom Gur",
        hours: 16,
        isModule: true,
        topics: [
          "Review of Classical Complexity",
          "Quantum Circuits & Universality",
          "BQP & Quantum Polynomial Time",
          "Quantum Query Complexity",
          "Grover's Lower Bound",
          "Quantum Communication Complexity",
          "Quantum Interactive Proofs",
          "QMA & Quantum Merlin-Arthur",
        ],
      },
      {
        id: "uqa",
        name: "Understanding Quantum Architecture",
        code: "UQA",
        lecturer: "Dr Prakash Murali",
        hours: 16,
        isModule: true,
        topics: [
          "Qubit Technologies Overview",
          "Quantum Gates & Gate Fidelity",
          "Quantum Error Correction Basics",
          "Surface Codes & Logical Qubits",
          "Quantum Compilation & Mapping",
          "Noise Models & Characterisation",
          "Quantum-Classical Interfaces",
          "Scaling Challenges & NISQ Era",
        ],
      },
    ],
  },
  lent: {
    label: "Lent Term",
    courses: [
      {
        id: "adcomarch",
        name: "Advanced Computer Architecture",
        code: "",
        lecturer: "Dr Robert Mullins",
        hours: 16,
        isModule: false,
        topics: [
          "Introduction, Trends & Fundamentals",
          "Advanced Pipelining",
          "Superscalar Processors",
          "Out-of-Order Execution",
          "Software Approaches to ILP (VLIW)",
          "Instruction Scheduling Techniques",
          "Multithreaded Processors (SMT)",
          "Memory Hierarchy & Caches",
          "Prefetching Techniques",
          "Vector Processors & SIMD",
          "Chip Multiprocessors & Coherence",
          "Cache Coherence Protocols",
          "Synchronization Primitives",
          "On-Chip Interconnection Networks",
          "Special-Purpose Architectures",
          "Converging Approaches to Design",
        ],
      },
      {
        id: "atfp",
        name: "Algebraic Techniques for Programming",
        code: "",
        lecturer: "Dr Neel Krishnaswami",
        hours: 16,
        isModule: false,
        topics: [
          "Algebraic Structures in Programming",
          "Monoids & Semirings",
          "Regular Expressions & Automata",
          "Algebraic Path Problems",
          "Shortest Path via Semirings",
          "Dataflow Analysis Algebraically",
          "Parsing as Algebraic Operations",
          "Advanced Applications",
        ],
      },
      {
        id: "crypto",
        name: "Cryptography",
        code: "",
        lecturer: "Dr Markus Kuhn",
        hours: 16,
        isModule: false,
        topics: [
          "Classic Ciphers & Perfect Secrecy",
          "Stream Ciphers & PRNGs",
          "Semantic Security & Computational Security",
          "Block Ciphers: DES, AES, Feistel",
          "Modes of Operation (ECB, CBC, CTR)",
          "Message Authentication Codes (MACs)",
          "Authenticated Encryption & GCM",
          "Hash Functions & Birthday Attacks",
          "Number Theory: Primes & Modular Arithmetic",
          "Diffie-Hellman Key Exchange",
          "Trapdoor Permutations & RSA",
          "RSA Attacks & OAEP",
          "Digital Signatures (ElGamal, DSA)",
          "Certificates & PKI",
          "Elliptic Curve Cryptography",
          "Quantum-Resistant Cryptography",
        ],
      },
      {
        id: "ecommerce",
        name: "E-Commerce",
        code: "",
        lecturer: "McTavish & Harris",
        hours: 8,
        isModule: false,
        topics: [
          "History of Electronic Commerce",
          "Network Economics & Metcalfe's Law",
          "Business Models & Web Design",
          "Payment Systems & Credit Cards",
          "Auctions & Mechanism Design",
          "Search Engines & Advertising",
          "Data Protection & Privacy Laws",
          "Internet Regulation & Legal Issues",
        ],
      },
      {
        id: "mlbayinfer",
        name: "Machine Learning & Bayesian Inference",
        code: "",
        lecturer: "Dr Sean Holden",
        hours: 16,
        isModule: false,
        topics: [
          "Bayesian Probability & Inference",
          "Naive Bayes & Generative Models",
          "Linear Regression & Regularisation",
          "Logistic Regression & Classification",
          "Kernel Methods & SVMs",
          "Gaussian Processes",
          "Neural Networks & Backpropagation",
          "Expectation-Maximisation (EM)",
          "Mixture Models & Clustering",
          "Dimensionality Reduction (PCA)",
          "Bayesian Model Comparison",
          "Monte Carlo Methods & Sampling",
          "Variational Inference",
          "Graphical Models & Belief Propagation",
          "Decision Theory & PAC Learning",
          "Ensemble Methods & Boosting",
        ],
      },
      {
        id: "optcomp",
        name: "Optimising Compilers",
        code: "",
        lecturer: "Dr Tobias Grosser",
        hours: 16,
        isModule: false,
        topics: [
          "Introduction & Compiler Structure",
          "Flow Graphs & Representations",
          "Peephole Optimisation",
          "Instruction Scheduling",
          "Dataflow Analysis: Live Variables",
          "Dataflow Analysis: Available Expressions",
          "Register Allocation by Colouring",
          "Common Sub-Expression Elimination",
          "Static Single Assignment (SSA) Form",
          "Abstract Interpretation",
          "Strictness Analysis",
          "Control Flow Analysis (Lambda Calculus)",
          "Points-to & Alias Analysis",
          "Instruction Selection (Target-Dependent)",
          "Phase-Order Problem",
          "Decompilation Techniques",
        ],
      },
      {
        id: "quantcomp",
        name: "Quantum Computing",
        code: "",
        lecturer: "Dr Herbert & Dr Murali",
        hours: 16,
        isModule: false,
        topics: [
          "Qubits & Quantum States",
          "Quantum Gates & Circuits",
          "Entanglement & Bell States",
          "Quantum Teleportation",
          "Deutsch-Jozsa Algorithm",
          "Simon's Algorithm",
          "Quantum Fourier Transform",
          "Shor's Algorithm (Period Finding)",
          "Shor's Algorithm (Factoring)",
          "Grover's Search Algorithm",
          "Amplitude Amplification",
          "Quantum Error Correction",
          "Quantum Key Distribution (BB84)",
          "Variational Quantum Algorithms",
          "Quantum Supremacy & NISQ",
          "Adiabatic Quantum Computing",
        ],
      },
      {
        id: "cc",
        name: "Cloud Computing",
        code: "CC",
        lecturer: "Dr Evangelia Kalyvianaki",
        hours: 14,
        isModule: true,
        topics: [
          "Cloud Models & Virtualisation",
          "Containers & Orchestration",
          "Distributed Storage Systems",
          "MapReduce & Spark",
          "Consistency & Replication",
          "Serverless Computing",
          "Auto-Scaling & Resource Management",
        ],
      },
      {
        id: "ce",
        name: "Computing Education",
        code: "CE",
        lecturer: "Dr Sue Sentance",
        hours: 16,
        isModule: true,
        topics: [
          "Theories of Learning in CS",
          "Computational Thinking",
          "Misconceptions & Concept Inventories",
          "Assessment Methods in CS Education",
          "Pedagogy for Programming",
          "Curriculum Design & Policy",
          "Diversity & Inclusion in CS",
          "Research Methods in CS Education",
        ],
      },
      {
        id: "cyc",
        name: "Cybercrime",
        code: "CYC",
        lecturer: "Prof Hutchings, Dr Clayton, Dr Hughes",
        hours: 16,
        isModule: true,
        topics: [
          "Defining Cybercrime & Typologies",
          "Malware & Botnets",
          "Phishing & Social Engineering",
          "Underground Markets & Ecosystems",
          "Denial of Service Attacks",
          "Fraud & Financial Cybercrime",
          "Policing & Regulation",
          "Prevention & Intervention",
        ],
      },
      {
        id: "dnn",
        name: "Deep Neural Networks",
        code: "DNN",
        lecturer: "Dr Huszar, Dr Antonova, Prof Lane",
        hours: 14,
        isModule: true,
        topics: [
          "Deep Learning Foundations & Optimisation",
          "Convolutional Neural Networks",
          "Recurrent Networks & Sequence Models",
          "Attention & Transformer Architectures",
          "Generative Models (VAEs, GANs)",
          "Diffusion Models",
          "Efficient Inference & Model Compression",
        ],
      },
      {
        id: "mh",
        name: "Mobile Health",
        code: "MH",
        lecturer: "Prof Mascolo & Dr Han",
        hours: 16,
        isModule: true,
        topics: [
          "mHealth Systems & Architecture",
          "Wearable Sensing & Physiological Data",
          "Activity Recognition & Context Awareness",
          "Audio & Speech Biomarkers",
          "Mental Health Monitoring",
          "Privacy & Ethics in Health Data",
          "Clinical Validation & Study Design",
          "ML for Health Applications",
        ],
      },
      {
        id: "mrs",
        name: "Mobile Robot Systems",
        code: "MRS",
        lecturer: "Prof Amanda Prorok",
        hours: 16,
        isModule: true,
        topics: [
          "Robot Kinematics & Dynamics",
          "Localisation & SLAM",
          "Path Planning & Motion Planning",
          "Multi-Robot Coordination",
          "Reinforcement Learning for Robotics",
          "Perception & Sensor Fusion",
          "Communication in Robot Teams",
          "Applications & Challenges",
        ],
      },
      {
        id: "msp",
        name: "Multicore Semantics & Programming",
        code: "MSP",
        lecturer: "Prof Sewell & Dr Harris",
        hours: 16,
        isModule: true,
        topics: [
          "Concurrency Models & Shared Memory",
          "Memory Consistency Models (SC, TSO)",
          "Relaxed Memory Models (ARM, POWER)",
          "C/C++ Concurrency & Atomics",
          "Lock-Free Data Structures",
          "Operational Semantics for Concurrency",
          "Verification of Concurrent Programs",
          "Real-World Multicore Challenges",
        ],
      },
    ],
  },
  easter: {
    label: "Easter Term",
    courses: [
      {
        id: "busseminrs",
        name: "Business Studies Seminars",
        code: "",
        lecturer: "McTavish & Harris",
        hours: 4,
        isModule: false,
        topics: [
          "Guest Lectures & Industry Talks",
          "Seminar Discussions & Case Studies",
        ],
      },
      {
        id: "hlogmodc",
        name: "Hoare Logic & Model Checking",
        code: "",
        lecturer: "Banerjee & Katsura",
        hours: 12,
        isModule: false,
        topics: [
          "Hoare Triples & Partial Correctness",
          "Proof Rules for Assignment, Sequence, If",
          "While Rule & Loop Invariants",
          "Total Correctness & Termination",
          "Weakest Preconditions",
          "Arrays & Pointer Reasoning",
          "Separation Logic Basics",
          "Introduction to Model Checking",
          "Temporal Logics (LTL, CTL)",
          "CTL Model Checking Algorithm",
          "Symbolic Model Checking & BDDs",
          "Abstraction & State Space Reduction",
        ],
      },
    ],
  },
};
export const ALL_COURSES_ORDERED: CourseWithTerm[] = Object.entries(COURSES_DATA).flatMap(([term, { courses }]) =>
  courses.map((c) => ({ ...c, term }))
);

export const VALID_COURSE_IDS = new Set(ALL_COURSES_ORDERED.map((c) => c.id));

